In [ ]:
# In colab run this cell first to setup the file structure!
%cd /content
!rm -rf MOL518-Intro-to-Data-Analysis

!git clone https://github.com/shaevitz/MOL518-Intro-to-Data-Analysis.git
%cd MOL518-Intro-to-Data-Analysis/Lecture_2

# Lecture 2: Working with Data

In Lecture 1 we used Python mostly as a calculator. Most biological experiments do not produce a single number, but rather a *collection* of measurements. Today we will learn how to represent those collections, store them in files, load them back into Python, and make our first plots.

The goals of this lecture are to:
1. Understand what an array is
2. Learn how to work with arrays in Python using NumPy
3. Create and manipulate arrates
4. Load and save a data files and inspect their contents  
5. Plot a simple time series from a data file




## What is an array?

An array is a collection of values that all represent the same kind of measurement.
You can think of it as a column in a spreadsheet.

Arrays are ordered and have a fixed length. Each element has a position, called an index.
Arrays show up everywhere in biology, e.g. time points, fluorescence intensities, cell sizes, gene counts, mass spectra.


### A 1D array as a table

This is a one dimensional array whose *values* go from `24` to `28`. To talk about their position within the array, we use their *index*, which starts at `0` and goes to `4`. So, the value at index `2` is `26`.

(Note, in Python we start the indexing at `0`. Other languages start at `1`, so be careful...)

| index | value |
|-------|-------|
| 0     | 24     |
| 1     | 25     |
| 2     | 26     |
| 3     | 27     |
| 4     | 28     |

<div style="text-align: center;">
  <img src="media/arrayindex_meme.jpg" width="500">
</div>

### A 2D array as a table

A two dimensional array looks like a small spreadsheet.

| row \ col | 0 | 1 | 2 |
|-----------|---|---|---|
| 0         | 1 | 2 | 3 |
| 1         | 4 | 5 | 6 |

This kind of structure appears naturally when recording data: each row is one observation, each column is one variable. Columns might represent Optical Density (OD) and Time if you were recording growth curves with bacteria e.g.


## External packages and `import`

Python itself is a small language.
Most scientific functionality lives in external packages.

A package is a collection of code written by other people.
NumPy and matplotlib are two examples we will use today.

The `import` command tells Python to load that code so you can use it.
We often give packages short nicknames to make code easier to read. Some of these are very standard (such as the `np` we use below) but for others you can use your own convention.

Finding packages is part of scientific programming, search and a little digging are you friends.


## NumPy and arrays

[NumPy](https://numpy.org/) is the main numerical package we will use in this course. It is a library for the Python programming language that provides arrays and tools for working with large collections of numbers.

To use the functions in NumPy, we need to `import` it like so:


In [1]:
import numpy as np

### Creating a 1D array

We can create an array from scratch by using the `np.array()` function. This command makes a 1D row array with the values 1, 2, 3, 4, 5.

In [52]:
arr = np.array([24, 25, 26, 27, 28])

If you type a variable's name without anything else on the line in a code cell, it will return the variable. So, if we type `arr`, we to see that it is an array and its elements.

In [34]:
arr

array([24, 25, 26, 27, 28])

### Length and shape

We can use NumPy arrays with standard Python functions. For example, the built-in `len()` function tells us how many elements are in a one-dimensional array.

In [35]:
print(len(arr))

5


The expression `arr.shape` (the name of the array followed by `.shape`) gives more detailed information. It tells us how many dimensions the array has, and how many elements there are along each dimension.

In [36]:
print(arr.shape)

(5,)


### Indexing and slicing

*Indexing* means getting a single element from an array by specifying its position (index). 
*Slicing* means getting multiple elements (a subset of the elements) from an array by specifying a range of indices.

Remember: **Python indexing starts at 0, not 1!**

#### Getting a single element (indexing)

To get the first element (at index 0), we use **square brackets**:

In [37]:
print(arr[0])

24


To get the last element, you can use a negative index. `arr[-1]` bascially means "one element from the end" (this is surprisingly useful sometimes).

In [38]:
print(arr[-1])

28


#### Getting multiple elements (slicing)

To get elements from index 0 up to (but not including) index 3:

In [39]:
print(arr[0:3])

[24 25 26]


Notice that `arr[0:3]` gives us elements at indices 0, 1, and 2, but NOT 3. The slice `[start:end]` includes the start but excludes the end!

We can also use a *step* to skip elements. This command gets every 2nd element:

In [40]:
print(arr[::2])

[24 26 28]


Here are some other useful ways to slice arrays:


In [41]:
# Get everything from index 1 to the end
print(arr[1:])


[25 26 27 28]


In [42]:
# Get all elements except the last one
arr[:-1]


array([24, 25, 26, 27])

*Using negative indices in slices is useful for getting elements relative to the end of the array.*

#### Practice with indexing and slicing

What do you think each of these will return? Predict yourself before running them.


In [43]:
print(arr[1])   

25


In [44]:
print(arr[2:5]) 

[26 27 28]


In [45]:
print(arr[-2]) 

27


### Replacing values

We can also replace one or more values in an array by indexing with square brackets.

In [51]:
print("before: ",arr)
arr[2] = 10
print("after: ",arr)

before:  [24 25 10 27 28]
after:  [24 25 10 27 28]


> Side note: the order you run cells matters. The computer will keep one copy of the array `arr` in memory. When you change it, it is then changed from then on. Go back and run the previous cell again. What happened? Why did it change? What can you do to make it behave as it did before?

### Creating a 2D array

In [53]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

`arr2` is a 2D array with elements 1,2,3 in the first row and 4,5,6 in the second two. We can ask for the dimensions and sizes of each dimension with `.shape`

In [57]:
print(arr2.shape)

(2, 3)


`arr2` is two dimensional (there are two numbers), with 2 rows and 3 columns.

### Indexing in 2D

With a 2D array, we need to specify both a row and a column. We use the format `arr2[row, column]`.

*Both row and column indexing start at 0...*


In [58]:
print(arr2[0, 1])

2


That gets the value `2` from row 0, column 1.

#### Getting an entire row

If we specify only the row and use `:` for the column, we get the entire row:


In [64]:
print(arr2[1,:])

[4 5 6]


This gives us the entire second row: `[4, 5, 6]`.

#### Getting an entire column

If we specify `:` for the row and a specific column, we get the entire column:


In [65]:
print(arr2[:, 0])


[1 4]


This gives us the entire first column: `[1, 4]`.

#### Practice with 2D indexing

What do you think each of these will return?


In [67]:
print(arr2[0, 0])

1


In [68]:
print(arr2[1, 2])

6


In [69]:
print(arr2[:, -1])

[3 6]


### Exercise 1

1. Create an 1D array whose elements are the odd numbers from 1 to 21. 
2. Print every third element of the array, i.e. every third odd number. 
3. Calculate how many odd numbers are between 1 and 21 if you skip every third odd number.

In [74]:
# Your code goes here





[ 1  7 13 19]
4


### Exercise 2

1. Create a 2D array with five rows and five columns whose elements are:

```
0 0 1 0 0
0 2 0 2 0
3 0 0 0 3
0 2 0 2 0
0 0 1 0 0
```
2. Print the third row.
3. Calculate the total number of elements. *Hint:* The `.shape` is actually an array, so you can index it to get the number of rows and columns. E.g. `arr.shape[0]` is the number of rows in the array `arr`.
4. Replace the last row with ```[99 99 99 99 99]``` and print the resultant array.


In [ ]:
# Your code goes here




## Loading data from a file

Of course, you aren't going to type in all of your data by hand! Your experimental data will be stored in files, so we need to learn to read and write them.

> In this course, each lecture folder will contain a `data/` directory with the relevant data files.

Let's load the OD1.csv file, which is a bacterial growth curve taken in the Gitai lab.


### Loading with `np.loadtxt`

NumPy has a built in function, `np.loadtxt`, for loading text-based data files like CSV (comma-seperated values) files.


In [ ]:
data = np.loadtxt('data/OD1.csv')

### Inspect the data first

It is often useful, especially when you are starting out and trying something for the first time, to inspect the data files after to load them to make sure the make sense.

First, this is data from a growth curve experiment, so we expect to see a 2D array with times and OD values.

In [ ]:
data.shape
data[:5]
data[-1]

### Extract columns

In [ ]:
time = data[:, 0]
od = data[:, 1]
time[:5], od[:5]

### Duration of experiment

In [ ]:
time[0], time[-1]
time[-1] - time[0]

## Saving modified data

When you modify data, save the result to a new file.
Do not overwrite raw data.


In [ ]:
od_modified = od * 1.0
od_modified[0] = 0.05
new_data = np.column_stack((time, od_modified))
np.savetxt('data/example2_modified.csv', new_data)

## Plotting

Numbers alone are hard to interpret.
Plots turn arrays into pictures that humans can understand.


### What is matplotlib?

Matplotlib is a plotting library.
It is not part of core Python.

It takes numerical arrays and turns them into figures.
We will start with a very small subset of its features.


In [ ]:
import matplotlib.pyplot as plt

### Plot OD versus time

In [ ]:
plt.plot(time, od)
plt.xlabel('Time')
plt.ylabel('Optical density (OD)')
plt.show()

### Normalizing the growth curve

In [ ]:
od_norm = od / od[0]
plt.plot(time, od_norm)
plt.xlabel('Time')
plt.ylabel('Normalized OD')
plt.show()

## In class exercises with files

Exercise 2: Load `example2.csv`, modify values, and save a new file.
Exercise 3: Load `OD1.csv` and `OD2.csv`, plot both, and discuss growth modes.


## Common failure modes

Forgetting imports.
Mixing up rows and columns.
Overwriting variables.
Not checking shapes or plots.
